# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:16
        auth:
          username: ndland
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    steps:
      - checkout
      - run: yarn build
  test:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - docker-hub
      - test:
          context:
            - docker-hub
          requires:
            - build